name: production
url: https://gcms.yourdomain.com
protection_rules:
  - required_reviewers:
      required_approving_review_count: 2
  - wait_timer:
      wait_time: 10
  - deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
  - required_status_checks:
      strict: true
      contexts:
        - "Backend Tests"
        - "Frontend Tests"
        - "Security Scan" 