name: Frontend Deployment

on:
  push:
    branches: [ main, develop ]
    paths: [ 'web-app/**' ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [staging, production]
        include:
          - environment: staging
            branch: develop
            if-condition: github.ref == 'refs/heads/develop'
          - environment: production
            branch: main
            if-condition: github.ref == 'refs/heads/main'

    if: ${{ matrix.if-condition }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: web-app/package-lock.json

    - name: Install dependencies
      working-directory: ./web-app
      run: npm ci

    - name: Build application
      working-directory: ./web-app
      env:
        VITE_API_URL: ${{ secrets.API_URL }}
        VITE_APP_ENV: ${{ matrix.environment }}
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./web-app
        vercel-args: '--prod'

    - name: Deploy to Netlify (Alternative)
      if: false # Set to true if using Netlify instead of Vercel
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './web-app/dist'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Deploy to GitHub Pages (Alternative)
      if: false # Set to true if using GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-app/dist
        publish_branch: gh-pages

    - name: Notify deployment
      run: |
        echo "✅ Frontend deployed to ${{ matrix.environment }}"
        echo "🌐 URL: ${{ secrets.FRONTEND_URL }}" 